/*H************************************************************************************************
 * FILENAME:        bluetooth_hal.c
 *
 * DESCRIPTION:
 *      Bluetooth Hardware Abstraction Layer (HAL), this source file provides an abstraction over
 *      the UART communications with the Bluetooth Low Energy (BLE) module (HC-08 v2.2).
 *
 * PUBLIC FUNCTIONS:
 *      void    BT_HAL_init()
 *      void    BT_HAL_sendMessage(const char* format, ...)
 *      void    BT_HAL_registerMessageCallback(BTCallback callback)
 *
 * NOTES:
 *      Every time that a reception interrupt is generated by the eUSCI module related to the
 *      Bluetooth the IRQHandler provided in this file will read the incoming message and invoke
 *      the callback function.
 *
 * AUTHOR: Simone Rossi    <simone.rossi-2@studenti.unitn.it>
 *
 * START DATE: 19 Feb 2024
 *
 * CHANGES:
 * DATE         AUTHOR          DETAIL
 */
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "bluetooth_hal.h"

#define BT_IN_BUFFER_SIZE 256       /* Max size of the unread message              */

BTCallback btCallback;                                  /* To call when a new message is ready */
volatile char incomingMessageBuffer[BT_IN_BUFFER_SIZE]; /* Contains the incoming message       */

void BT_HAL_init() {}

void BT_HAL_sendMessage(const char *format, ...) {}

void BT_HAL_registerMessageCallback(BTCallback callback) { btCallback = callback; }

void BT_HAL_forwardAndReset() {
    if (btCallback != NULL)
        btCallback(incomingMessageBuffer);
}

void BT_HAL_triggerMessageReceived(const char* message) {
    strcpy(incomingMessageBuffer, message);
    BT_HAL_forwardAndReset();
}